### ISSUE TITLE
Theme creation works only partially

### ISSUE THREAD

**Issue by bronger** [rdmorganiser/rdmo#102]
I work along the lines of https://rdmo.readthedocs.io/en/latest/configuration/themes.html#working-with-themes for branding our RDMO instance. While overriding `home_text_en.html`, `base_footer.html`, and `variables.scss` worked, our new favicon as well as the new font configuration are ignored.  This is our directory structure of the theme:

```
templates/core/home_text_de.html
templates/core/home_text_en.html
templates/core/base_footer.html
static/core/img/favicon.png            # is ignored
static/core/css/variables.scss
static/core/css/fonts.scss             # is ignored
```

We use RDMO 0.11.0.

**Comment by triole** [comment]
I tried to reproduce the problems you were experiencing. Unfortunately without success because my favicon and font settings were applied correctly. I used the directory structure mentioned below which looks the same as yours. 

```
.
├── static
│  └── core
│     ├── css
│     │  ├── fonts.scss
│     │  └── variables.scss
│     └── img
│        └── favicon.png
└── templates
   └── core
      ├── base.html
      ├── base.html.py
      ├── base_footer.html.py
      ├── base_head.html
      ├── base_head.html.py
      ├── base_navigation.html
      └── base_navigation.html.py
```

I am having a hard time to point out the reason of your difficulties. My suggestion would be that you try to restart your RDMO instance, delete your browser cache and check again. Please let me know if anything helped.

**Comment by bronger** [comment]
I found the cause.  Actually, two things were wrong on my side. `manage.py collectstatic` didn’t find the theme because (1) the theme was created after this command (easily solved) and (2) `THEME_DIR` was not set.

Now you may ask, how could this stupidity happen?  Well, in a container …

The Dockerfile runs `collectstatic`, but the configuration is mounted to the container not before runtime.  This configuration contains `THEME_DIR`.  Thus, the solution was to add a temporary configuration with a `THEME_DIR` to the image itself.

Sorry for the noise!
