### ISSUE TITLE
File name truncated for export in Firefox

### ISSUE THREAD

**Issue by cfgmr** [rdmorganiser/rdmo#110]
Hi, 

when I export a view as Rich Text Format, Open Office, Microsoft Office, Markdown, mediawiki or LaTeX (i.e. any format which can not be rendered by the browser directly), the file name of the created file is truncated (e.g. exported as *MOSES*, without file extension, instead of *MOSES Eddy Study II Cap Verde.tex*:

![image](https://user-images.githubusercontent.com/27813785/52204450-74a81280-2874-11e9-91bc-2bfe4638cadf.png)

This issue occurs in Firefox (64.0.2 on macOS 10.12.6), with Chrome, everything works as expected:

![image](https://user-images.githubusercontent.com/27813785/52204634-0879de80-2875-11e9-9642-b8e500ed0599.png)

**Comment by triole** [comment]
This problem seems to boil down to the `Content-Disposition` entry in the response header. Mozilla says that the filename in this entry needs to be surrounded by double quotes. If it is the problem you are experiencing should not occur.

http://kb.mozillazine.org/Filenames_with_spaces_are_truncated_upon_download

I checked the network traffic when triggering a download. My response header looked like this:

```
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Wed, 06 Feb 2019 10:53:42 GMT
Content-Type: application/tex
Content-Length: 3
Connection: close
Content-Disposition: attachment; filename="this is a nice project.tex"
Content-Language: en
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
```

As you can see the filename is correctly surrounded by double quotes. Furthermore I did not have the problem that you are having. The only difference between our two setups seems to be that I am on a Linux machine and you are on a Mac.

I will test it on a Mac later when I have one at hand. At the moment I do not have an idea what could be the reason for your difficulties because the response header looks okay and my browsers behave correctly. Maybe it has to do with some web server setup? But just guessing.

**Comment by cfgmr** [comment]
This seems to be the problem, the file name is not in double quotes:
```
Response headers:
HTTP/1.1 200 OK
Date: Wed, 06 Feb 2019 11:07:53 GMT
Server: Apache/2.4.18 (Ubuntu)
Vary: Accept-Language,Cookie
X-Frame-Options: DENY
Content-Language: en
Content-Disposition: attachment; filename=MOSES Eddy Study II Cap Verde.tex
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Content-Length: 12207
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/tex
```
Seems to be a web server problem rather than a Mac issue? 🤷‍♂️ 
The RDMO instance is hosted at GFZ (https://rz-vm422.gfz-potsdam.de) if you want to dig deeper.

**Comment by triole** [comment]
Looking into the RDMO source code everything seems to be correct. Checking exactly the string that gets written into the response header you can see that there are quotes. This is what the log entry of the string looks like.

```
2019-02-07 12:00:00,576 [INFO] /src/rdmo/rdmo/core/utils.py 142: attachment; filename="another nice test project.rtf"
```

Maybe the hosting Apache is responsible for your problem. Is there any kind of header rewrite? This is the best idea I have at the moment.

**Comment by cfgmr** [comment]
Thank you for looking into this. I will contact the admin for the RDMO instance to let them know what you found out. I'll just use chrome from now on to avoid the problem. 👍
