### ISSUE TITLE
Text formatting in catalog missing (line breaks)

### ISSUE THREAD

**Issue by Bassbiest** [rdmorganiser/rdmo#117]
### Summary
Text formatting in question catalogs is confusing/missing and gets removed upon export and reimport.

### In detail
While working on the [RDMO catalog](https://github.com/rdmorganiser/rdmo-catalog/issues/5), I did some changes and wanted to test these and imported the catalog via command line into my local RDMO instance. I managed to get the lists working but I never got the line breaks, that I added, to be visible in my RDMo instance. Then I started to test a little.

### Steps to recreate the test
I made a new catalog called "linebreak" in my RDMO instance, with only one question and added the following text as question text and help text:
```
some random text (enter)
some random text (double space)  
some random text (dot) .
some random text (slash) /
some random text (backslash) \
some random text (html br) <br />
some random text (xml xA) &#xA;
some random text (xml xD) &#xD;
last line
```
Immediately I looked at the result from the project's point of view (using the app itself) and saw this:

![ui_prior_export](https://user-images.githubusercontent.com/30717374/53567475-9dfc4b80-3b5f-11e9-9a8b-74d3e6ff164a.PNG)

Most of the methods I tried failed, but some did, in fact, create a line break. Although I technically used the enter button on every line, you can see it didn't do much. Anyway, I exported the catalog as an XML file to see what the line breaks look line in code so I could use them. The result was:

```

some random text some random text some random text. some random text/ some random text\ some random text <br /> some random text &#xA; some random text &#xD;

```
Then, I added a second question to the XML file with the same text that I used to create line breaks in the app and reimported the catalog to my instance with the following result:

![reimported](https://user-images.githubusercontent.com/30717374/53567823-a6a15180-3b60-11e9-9f26-f0cab1a10b82.PNG)

So all methods that do work in the app, do not work anymore upon reimport. I think it is also important to note that the `<br />`-tag makes all the text after it disappear. 

Hopefully, I didn't miss any obvious hint or rule which would have helped me right from the get-go.

**Comment by Bassbiest** [comment]
I figured out that adding a blank line in between paragraphs to the xml file does indeed show line breaks in the RDMO instance I am working with. However, upon export (to xml) the line breaks get removed again.

### Example
```
first line

second line
third line
```

*in xml produces*

first line  
second line third line

**Comment by triole** [comment]
The RDMO text editor fields do not support rich text or any kind of formating characters. This is an intentional choice to keep things simple and the reason that all these different formatting characters are ignored.

As I see it this is going into the direction of a discussion about changing this behavious and possibly implement some kind of rich text support. We should take the time to discuss and carefully think about it.

**Comment by jmfrenzel** [comment]
I agree, on not supporting rich text. However, don't we have a problem allowing html in rdmo-catalog text?


The current problem is, that blank lines are omitted/deleted in rdmo export as well as content is missing on xml import which destroys all formatting (paragraphs  and enumerations). Was this intentionally introduced as part of the re-factoring of import/export functionality in [rdmo v0.11.0 
release notes](https://github.com/rdmorganiser/rdmo/releases/tag/0.11.0)?

For example  [rdmo-catalog v0.1.0](https://github.com/rdmorganiser/rdmo-catalog/tree/v0.1.0) provided all this functionality. After the change of the data model in [rdmo v.0.11](https://github.com/rdmorganiser/rdmo/releases/tag/0.11.0) the functionality seems lost. This is in line with current master [rdmo-catalog 74e7350](https://github.com/rdmorganiser/rdmo-catalog/commit/74e73503527213d0fcd9ebd48d8ba43fb545421b) missing paragraphs and enumeration.

**Comment by Bassbiest** [comment]
I also agree not to provide rich text formatting, but the basic features, which are already implemented, need to be made obvious and consistent on how to use to the user. This includes:
- bold
- italic
- lists
- paragraphs
- maybe more

And this is/should be the purpose of this issue as it is crucial for readability of question/help texts. 

Still, the above-demonstrated testing revealed other issues that should be acknowledged for. I will list them here but leave it to you on how to approach them i.e. open new issues etc.

- formatting when using RDMO editor is inconsistent between question and help text
- export
  - removes parentheses and their content, line breaks and spaces if more than one is present (might be bad for concatenated lists)
- import
  - removes line breaks, spaces 
  - parses HTML in the case of anchor tags `<a>` (which is necessary) but breaks in case there is a break tag `<br>`, which makes the program ignore everything after it

**Comment by triole** [comment]
I reinvestigated the issue. Here is what I found out:

The data are written correctly into the database. Line breaks and everything is there. The same is true for xml files. I exported several projects as xml and reimported these files. The data including line breaks were there.

Where we may have a problem is in rendering the answers. When rendering the view template Django does escape html characters which prevents the browser from rendering them. This is intentional because we do not want everybody to paste html that is treated as such into the webpage. We could simply switch it off but I am not sure if this is a good idea. Maybe there is another solution to render formated. I will investigate.

As said I was not able to reproduce data loss in exported xml files. Maybe I did something wrong. If you could send example files containing the formating that made the issues occur I would have a better chance to dispel eventual misunderstandings.

I tried with the following and they were fine on xml basis.
```
text (enter)
text (double space)  
text  (dot) .
two empty lines


-----
text (slash) /
text (backslash) \
text (html br) <br />
text (xml xA) &#xA;
text (xml xD) &#xD;
last line
```
