### ISSUE TITLE
Broken page layout in IE11

### ISSUE THREAD

**Issue by jploski** [rdmorganiser/rdmo#129]
Please consider adding `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` to rdmo/core/templates/core/base_head.html. As per version 0.13, the page layout looks completely broken in IE11 because of this.

**Comment by jochenklar** [comment]
Thanks, we will add it in the next release.

**Comment by triole** [comment]
I tend not to include the mentioned meta tag into the html code. This is for several reasons.

The compatibility tag was introduced in IE8 and disabled in IE11. That is why it does only
affect IE8, IE9 and IE10. Since we do not support these old IE versions there does not seem
to be a reason to add the meta tag to our html code.

Here is what [Microsoft has to say](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)#document-mode-changes):
```
Starting with IE11, document modes are deprecated and should no longer be used, except on a temporary basis. Make sure to update sites that rely on legacy features and document modes to reflect modern standards.
```

Furthermore best practice recommends to add the directive to the server's response header. Because it tells the IE which rendering mode to use before having started to render the html. Being inside the html the tag causes the IE to abort rendering and start from the beginning which obviously is a performance hit.

**Comment by jploski** [comment]
> I tend not to include the mentioned meta tag into the html code. This is for several reasons.
> 
> The compatibility tag was introduced in IE8 and disabled in IE11. That is why it does only
> affect IE8, IE9 and IE10. Since we do not support these old IE versions there does not seem
> to be a reason to add the meta tag to our html code.

You're right. Upon further investigation the affected version of IE11 appears to be configured to show local Intranet sites in "compatibility mode", probably because of other broken web pages that still need it. That's why this tag has effect it and is required in my environment.

> If you are really sure that you require the compatibility tag maybe you could make your server's response deliver it.

Yes, that sounds like a good workaround (certainly better than patching the HTML page on every update).

> By the way I checked the RDMO page in my IE11 and it did not look ridiculously strange compared to IE standards. Can you specify a little more what you meant by `completely broken`?

If you go to "Tools > Compatibility View Settings" and add the URL of your site there, you can see what broken looks like. Basically, the whole screen is covered by huge images and you have to scroll down all the way to even see the login form. Probably not many users are affected by this, but for those who are, this is the "first impressions".

**Comment by triole** [comment]
Thank you for your response. I consider the issue being settled and close it.
