### ISSUE TITLE
Round input from range widget.

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#137]
In certain browsers the range widget gives values like 7.0000000000000001.

**Comment by triole** [comment]
The problem was reproduced in Chrome. It seems to be a browser issue as Chrome is sending odd values to the RDMO backend although different ones were picked in the range selector.  Firefox does not do that.

Here is what the [Angular Docs](https://docs.angularjs.org/api/ng/input/input%5Brange%5D) say:
```However, step is currently only fully implemented by Firefox. Other browsers have problems when the step value changes dynamically - they do not adjust the element value correctly, but instead may set the stepMismatch error. If that's the case, the AngularJS will set the step error on the input, and set the model to undefined.```

**Comment by triole** [comment]
Fixed and pushed into master. 

See https://github.com/rdmorganiser/rdmo/commit/b58ed5c74ba639f88952c4d84008b8d920437e2a
