### ISSUE TITLE
project authors can not remove themselves from project

### ISSUE THREAD

**Issue by Bassbiest** [rdmorganiser/rdmo#139]
Since I can't delete a project I was added to (see #138 ) I tried to remove myself from the member list but there is no option to do that either. Hence, the project is stuck in my list of projects.

**Comment by jochenklar** [comment]
Thanks for reporting, this will be fixed soon.

**Comment by triole** [comment]
Being fixed in https://github.com/rdmorganiser/rdmo/tree/remove_project_members. Will be merged into master and be available with the next release.

Project owners will then be able to remove themselves unless they are not the only remaining project owner. If this is the case the button to remove won't be available because a project does require an owner.

**Comment by harenk** [comment]
While the technical ability to do so should be available, I think this is also a policy issue: a project, as an assembly of members, should have the ability to make up a member policy:usually becoming/being member of a project is not only an individual act of decisions, it's as much a decision of the project. 
Thus I feel the removal of a member by himself should be a project's policy decision.  
RDMO should offer this to the project's policy makers, e.g. by a checkbox to allow/disallow individual removal of a member.

**Comment by jochenklar** [comment]
A new workflow was introduced in RDMO 1.5. People can now "leave" a project unless they are the last "owner".
