### ISSUE TITLE
Django 3.0

### ISSUE THREAD

**Issue by hardfalcon** [rdmorganiser/rdmo#166]
Django 3.0 has been released, and the current version of RDMO seems to be incompatible with it.

A quick fix would be the change I had already suggested in #147.

Btw, the [release notes for Django 2.2.8](https://github.com/django/django/blob/2.2.8/docs/releases/2.2.8.txt) state that it fixes a security issue with django-admin, but that this fix may be a breaking change for some applications that rely upon the old/insecure behavior. We have done some superficial testing and couldn't find any issue, but I guess it won't hurt if somebody more familiar with RDMO's inner workings also has a look at this. I could also well imagine that the changed behavior in Django 2.2.8 might cause problems for #140.

**Comment by jochenklar** [comment]
We changed the requirements to use the compatible release clause `~=`. This is probably the most pythonic" way.

We will check the Django 3 compatibility later, we probably only need to remove `six` somewhere.

**Comment by triole** [comment]
An update to Django3 shouldn't pose a problem. I have already prepared it in the following branch: https://github.com/rdmorganiser/rdmo/tree/django3.

Django3 requires at least Python3.6. We need to carefully think about when to merge the update into master because not everybody maybe running a sufficient Python version at the moment.

**Comment by jochenklar** [comment]
RDMO 1.6 will run with Django 3.2 (and Python >=3.6).
