### ISSUE TITLE
jQuery and Bootstrap Vulnerabilities

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#172]
RDMO currently defines settings (vendor-section) with jQuery and Bootstrap versions that are vulnerable. Is there any requirement for the particular version or can they be safely upgraded? I used the https://github.com/lirantal/is-website-vulnerable tool to check this:

```
- Setting up a chrome instance
✔ Set up completed in 0.54 seconds!
- Auditing...
✔ Auditing completed in 2.37 seconds!

  Website: https://..../
  
    ⎡ ✖ Bootstrap@3.3.7
    ⎜ ■■■  5  vulnerabilities
    ⎣ ▶︎ https://snyk.io/vuln/npm:bootstrap?lh=3.3.7
  
    ⎡ ✖ jQuery@3.2.1
    ⎜ ■■■  1  vulnerabilities
    ⎣ ▶︎ https://snyk.io/vuln/npm:jquery?lh=3.2.1
  
  [6] Total vulnerabilities
  [2221.18ms] execution time
  vulnerabilities powered by Snyk.io (https://snyk.io/vuln?type=npm)
```

**Comment by triole** [comment]
Thank you for reporting. I already updated the vendor files and pushed the changes to `master`. Now we are using the latest jQuery version. Unfortunately for Bootstrap it is a little more complicated. I tried the latest version as well but stumbled across problems occurring with v4 and higher. For now we are on 3.4.1 which is the latest of the version 3 family.

We'll need to have a deeper look into it to be able to update to Bootstrap 4.

**Comment by mstuehrenberg** [comment]
I have made the update to 1.0.3 on our test instance, which has local vendor files by using
`python manage.py collectstatic`.

I wondered if the updated bootstrap and jQuery files will be updated as well and found a couple of jQuery files, i.e.

```
./static_root/rest_framework/js/jquery-3.3.1.min.js
./static_root/admin/js/vendor/jquery/jquery.min.js
./static_root/jquery/jquery-3.2.1.min.js
./vendor/jquery/jquery-3.2.1.min.js
./env/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/jquery-3.4.1.min.js
./env/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js
```

I did a 
`python manage.py collectstatic`
again with the following result

```
./static_root/rest_framework/js/jquery-3.3.1.min.js
./static_root/rest_framework/js/jquery-3.4.1.min.js
./static_root/admin/js/vendor/jquery/jquery.min.js
./static_root/jquery/jquery-3.2.1.min.js
./vendor/jquery/jquery-3.2.1.min.js
./env/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/jquery-3.4.1.min.js
./env/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js
```

Under `/static_root/jquery/` there is still the 3.2.1 version.
As a result, the menus in RDMO did not work anymore, since 
`<URL>/static/jquery/jquery-3.4.1.min.js`
resulted in a 404.

I have copied the `jquery-3.4.1.min.js` from `env/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/` to `static_root/jquery/` to fix that.

In addition, the same is true for the bootstrap.min.js and bootstrap.min.css, which I therefore copied to the ` static_root/bootstrap/js/` and `static_root/bootstrap/css/` directories respectively.

So, in addition in updating the vendor files it would be nice to state what has to be done to update the local vendor files as well.

**Comment by jmfrenzel** [comment]
Release [1.0.3](https://github.com/rdmorganiser/rdmo/releases/tag/1.0.3) includes updates in vendor files. 
This implies a 
`python manage.py download_vendor_files`
before the 
`python manage.py collectstatic`

**Comment by mstuehrenberg** [comment]
Thanks, I confirm that this worked.

**Comment by jochenklar** [comment]
Hi!

- I will fix `download_vendor_files` to first delete everything in `vendor`
- `python manage.py collectstatic -c` should delete all static files before collecting (https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#cmdoption-collectstatic-clear).

**Comment by jochenklar** [comment]
I updated `download_vendor_files`, `deploy` and the documentation. Closing here.
