### ISSUE TITLE
[enhancement] E-Mail Notifications for Membership Changes

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#182]
For production usage it is highly relevant that users are notified in case they get permissions to projects inside the RDMO. So, like in Gitlab and many other platforms, RDMO should sent a mail to the new user when permissions are granted. In general further notifications for e.g. project handling might be added.

**Comment by jochenklar** [comment]
Hi, @m6121 , and sorry that it took so long for us to reply. We didn't not implement this feature since it could be used to "spam" random people with invites. However, this was probably to much of worry about missuse.

We are planning to refactor the project-membership workflow, and this feature will be implemented, probably like GitLab handles it.
