### ISSUE TITLE
incorrect export of options

### ISSUE THREAD

**Issue by xokoxk** [rdmorganiser/rdmo#206]
an exported set of options includes the tag \<text\>, which should be <title>. The import expects the <title> tag.
Presumably an issue in https://github.com/rdmorganiser/rdmo/blob/master/rdmo/options/serializers/export.py

**Comment by triole** [comment]
I have difficulties to understand what kind problem you have observed because I can not find any `<text>` tags in exported xml files containing options. My imports of these files also went well. What do you mean by "the import expects the <title> tag".

Please could you explain a little more? What did you do? Which kind of error did occur?

**Comment by xokoxk** [comment]
ooops, sorry - i got the description of the issue all mixed up. The tag-problem is actually the other way round: An exported set of options includes the tag <title>, but it actually should be <text> (see e.g. https://github.com/rdmorganiser/rdmo-catalog/blob/master/rdmorganiser/options/rdmo.xml). 

if an imported option does not include the <text> tag, the option has no "name" - for the user, the option will be available, but there is no text to it. Since the import is still successful, there is no error message.
So, when you reproduced the options import, you did create new options, but they (presumably) don't have any text. 

I hope I could clear this one up -  sorry for the confusion.

**Comment by triole** [comment]
Thank you, your explanation helped a little. I understood that you get options xml files that do have `<title>` instead of `<text>`. As obviously this does not work because the import wouldn't find any text belonging to these "broken" options. So far so good. 

My only problem is that my export does not behave like this. When I export from my local RDMO there is not a single `<title>` inside my xml file. So I am really interested in how you achieved that? Unfortunately I lack an illuminating idea. Which RDMO version are you running? Do you have any kind of modifications? Sorry, that I am asking but I do not know where to look.
