### ISSUE TITLE
[1.6-rc.1] Language Switch in Template

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#374]
Hi,

currently, a part of the language switch is implemented inside the `core_tags` function `i18n_switcher()`. However, when using a custom templates, one might also want to change the language switch in order to meet the rest of the UI. It would be very helpful, if this tag would be refactored into a template. To enable this, it should be sufficient to make the `settings.LANGUAGES` as well as the currently selected language available in the template and use the built-in template tags.

What are your thoughts about this? I can also raise a PR implementing this feature.

Best regards

**Comment by jochenklar** [comment]
Hi @m6121 , I think this can be already done with Django build-in tags. See: https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#switching-language-in-templates.

Otherwise we could add `LANGUAGES` to `SETTINGS_EXPORT` (https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#switching-language-in-templates, we are using https://github.com/jakubroztocil/django-settings-export). You could also overwrite  `SETTINGS_EXPORT` in your `local.py`.

**Comment by m6121** [comment]
Thanks for pointing me towards the translation tags! All requirements are already there. So, instead of
https://github.com/rdmorganiser/rdmo/blob/219cc2eaecacd8806e5dec97a9c9c96c4e9d1bd8/rdmo/core/templates/core/base_navigation.html#L84

one might use (and modify) the following code in the template:

```
{% get_available_languages as LANGUAGES %}
{% get_current_language as CURR_LANGUAGE %}
{% for lang_code, lang_name in LANGUAGES %}
    {% if lang_code == CURR_LANGUAGE %}
        <li><a href="{% url 'i18n_switcher' lang_code %}"><u>{{ lang_name }}</u></a></li>
    {% else %}
        <li><a href="{% url 'i18n_switcher' lang_code %}">{{ lang_name }}</a></li>
    {% endif %}
{% endfor %}
```

**Comment by jochenklar** [comment]
@triole maybe we should add that to the language-in-themes-docs as well.
