### ISSUE TITLE
RDMO export with image included

### ISSUE THREAD

**Issue by cpfaff** [rdmorganiser/rdmo#385]
He there

I wanted to use rdmo and the render_to_format function returning a dmp PDF which follows our own branding including images. So far I created a view and an html template in our Django project also embedding our logo (using static content in: /static/images/logo.png). Rendering the template as html works fine. Tossing that html into the render_to_format function I see pandoc failing for the embedded image not being found as it treats the static image path as absolute path on the filesytem (so it starting from root. when I put the image there it works). Do you have any suggestions or ideas on how to best deal with it to make pandoc find the image served in the context of django static files?

Best Claas

**Comment by cpfaff** [comment]
He @jochenklar. Thanks for the fast reply. I see...Yeah I think you suggestion might a useful addition.

**Comment by cpfaff** [comment]
I think it would also be super useful if I could pass a custom latex template to `pandoc` through a parameter in your render to format function. That way we gain a lot of flexibility adjusting the style of the output format? What do you think?

**Comment by triole** [comment]
I added the requested feature to this branch: https://github.com/rdmorganiser/rdmo/tree/export_with_image

With the changes Pandoc is able to find static files and export them into documents. In the view these files are referenced by their standard url so that they can be rendered in the browser as well. You could write something like this into your view:

```
<img src="/static/my_own_logo.png">
```

**Comment by cpfaff** [comment]
Nice thanks!
