### ISSUE TITLE
Fix grammatical gender for vebose name in help texts

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#59]
For certain Sets and in German, the creation of the help text produces wrong grammar.

**Comment by vanessaga** [comment]
I would like to draw your attention to one thing that we noticed (University Library at the LMU) in the DFG questionnaire for economics and social sciences. It is about text passages that are automatically supplemented by variables. The variables are replaced with nouns such as "establishment", "data set" or "set", so that the German articles / pronouns unfortunately do not always match. Some examples are attached. The affected text passages can be adjusted in the django.po file (screenshot also attached). If we correct it there, it either fits in one place or in the other, but not all at the same time. ![screenshot_frontend1](https://user-images.githubusercontent.com/50202765/116989573-36f3f780-acd2-11eb-9cb2-38101d28779f.jpg)
![screenshot_frontend2](https://user-images.githubusercontent.com/50202765/116989575-378c8e00-acd2-11eb-808b-672e26696671.jpg)

**Comment by jochenklar** [comment]
Hi @vanessaga , yes, we need to do something about this. The one with the Benutzerkonto seem just a typo in the .po file, we we will fix asap.
