### ISSUE TITLE
translation of empty fields for title or help text of a question

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#614]
### Rationale / Begründung

Currently, when a field is left empty (`''`) and translated by the [`TranslationMixin`](https://github.com/rdmorganiser/rdmo/blob/89961b02fe5a9bfd8ce58c347406d053e7b26270/rdmo/core/models.py#LL30C7-L30C23), another language with a non-empty field is returned. 
In some cases this can be desirable but in others not. For example, when the help text of a question is defined for one language and missing for another..
[This line](https://github.com/rdmorganiser/rdmo/blob/89961b02fe5a9bfd8ce58c347406d053e7b26270/rdmo/core/models.py#LL38C9-L38C10) a makes empty fields return `None` instead of `''` and skips to find other language fields. Is this a bug or feature?
```py
 r = getattr(self, '%s_%s' % (field, lang_field)) or None
```

### Affected 

Users

### Minimal functionality

* return an empty string when a field for a certain language is left empty

### Nice-to-have functionality

* have a setting to return empty fields or find next non-empty language field

### References / Verweise

* https://github.com/rdmorganiser/rdmo/blob/89961b02fe5a9bfd8ce58c347406d053e7b26270/rdmo/core/models.py#LL38C9-L38C10

**Comment by Zack-83** [comment]
Actually this setting creates often problems, because it does not apply to uniformly to all fields. Having a look to all empty answers for a given project, we get fields containing `'None'`, fields containing the empty string `''`, fields really empty, fields not initiated. As a consequence, in order to reuse the information, either via the JSON API or within a Django view, you need a messy chain of `%if%`-conditions.
If that brings no unpleasant consequences, I would suggest to remove the part `or None`.

**Comment by MyPyDavid** [comment]
we can add a setting to enable/disable this feature (feature flag)?

**Comment by MyPyDavid** [comment]
in [1.11.0](https://github.com/rdmorganiser/rdmo/releases/tag/1.11.0) with settings `REPLACE_MISSING_TRANSLATION`
